# Customized Python script for pNet workflow, built at 2023-10-03 11:29:22
# Generated by running python pNet.workflow_guide()
# To run this python code, use the terminal command line below
# python ./Test_Workflow.py

# Load packages
import pNet

# setup and run a customized workflow
pNet.workflow_simple(
    dir_pnet_result='/Users/yuncongma/Documents/Document/fMRI/Myworks/pNet/Example/HCP_Surface/Data/Test',
    dataType='Surface',
    file_scan='/Users/yuncongma/Documents/Document/fMRI/Myworks/pNet/Example/HCP_Surface/Data/Scan_List.txt',
    dataFormat='HCP Surface (*.cifti, *.mat)',
    file_Brain_Template='/Users/yuncongma/Documents/Document/fMRI/Myworks/pNet/Brain_Template/HCP_Surface/Brain_Template.json',
    K=17,
    Combine_Scan=False
)

