function Color_Function=fColor_Theme(Theme,Parameter,varargin)
% Designed By Yuncong Ma, Apr. 5, 2020
% To get default color function setups
% Color_Function=fColor_Theme(Theme,Parameter)
% eg. Color_Function=fColor_Theme('Seed_Map',[min_CC,Threshold,max_CC])
% eg. Color_Function=fColor_Theme('Seed_Map_2',[min_CC,max_CC])
% eg. Color_Function=fColor_Theme('Seed_Map_3',[min_CC,max_CC])
% eg. Color_Function=fColor_Theme('Seed_Map_Positive',[min_CC,Threshold,max_CC])
% eg. Color_Function=fColor_Theme('Seed_Map_Positive_Only',[min_CC,Threshold,max_CC])
% eg. Color_Function=fColor_Theme('Seed_Map_3_Positive',[min_CC,max_CC])
% eg. Color_Function=fColor_Theme('FC',max_CC)
% eg. Color_Function=fColor_Theme('Atlas',Max_Index)
% eg. Color_Function=fColor_Theme('Gray_Scale',[Min_Value,Min_Gray,Max_Value,Max_Gray])
% eg. Color_Function=fColor_Theme('Rainbow',[Min_Value,Max_Value])
% eg. Color_Function=fColor_Theme(_,_,{'Darker',0.8})

Options.Darker=1;
Options=fOption('fColor_Theme',Options,varargin);
if isempty(Options)
    return;
end

if ~(Options.Darker>=0 && Options.Darker<=1)
    error('Error in fColor_Theme: Darker should be in [0,1]\n');
end

switch Theme
    case 'Seed_Map'
        min_CC=Parameter(1);
        Threshold=Parameter(2);
        max_CC=Parameter(3);
        Color_Function=...
            [-max_CC,0,1,1;...
            -Threshold,0,(Threshold-min_CC)/(max_CC-min_CC),1;...
            -Threshold,0,0,0;...
            0,0,0,0;...
            Threshold,0,0,0;...
            Threshold,1,(Threshold-min_CC)/(max_CC-min_CC),0;...
            max_CC,1,1,0];
    case 'Seed_Map_2'
        min_CC=Parameter(1);
        max_CC=Parameter(2);
        Color_Function=...
            [-max_CC,0,1,1;...
            -min_CC,0,0,1;...
            -min_CC,0,0,0;...
            0,0,0,0;...
            min_CC,0,0,0;...
            min_CC,1,0,0;...
            max_CC,1,1,0];
    case 'Seed_Map_3'
        min_CC=Parameter(1);
        max_CC=Parameter(2);
        Color_Function=...
            [-max_CC,0,1,1;...
            -[min_CC,max_CC]*[0.7,0.3]',0,0,1;...
            -min_CC,0,0,0.5;...
            -min_CC,0,0,0;...
            0,0,0,0;...
            min_CC,0,0,0;...
            min_CC,0.5,0,0;...
            [min_CC,max_CC]*[0.7,0.3]',1,0,0;...
            max_CC,1,1,0];
    case 'Seed_Map_Positive'
        min_CC=Parameter(1);
        Threshold=Parameter(2);
        max_CC=Parameter(3);
        Color_Function=...
            [0,0,0,0;...
            Threshold,0,0,0;...
            Threshold,1,(Threshold-min_CC)/(max_CC-min_CC),0;...
            max_CC,1,1,0];
    case 'Seed_Map_Positive_Only'
        min_CC=Parameter(1);
        Threshold=Parameter(2);
        max_CC=Parameter(3);
        Color_Function=...
            [Threshold,0,0,0;...
            Threshold,1,(Threshold-min_CC)/(max_CC-min_CC),0;...
            max_CC,1,1,0];
    case 'Seed_Map_3_Positive'
        min_CC=Parameter(1);
        max_CC=Parameter(2);
        Color_Function=...
            [min_CC,0,0,0;...
            min_CC,0.5,0,0;...
            [min_CC,max_CC]*[0.7,0.3]',1,0,0;...
            max_CC,1,1,0];
    case 'FC'
        max_CC=Parameter(1);
        Color_Function=...
            [-max_CC,0,1,1;...
            0,0,0,1;...
            0,1,0,0;...
            max_CC,1,1,0];
    case 'Atlas'
        Color_Table=Load_Mathematica_Mat(fullfile(fileparts(mfilename('fullpath')),'Color_Table.mat'));
        Max_Index=Parameter;
        Color_Function=zeros(2*Max_Index+1,4);
        Color_Function(1,1)=0.5;
        for i=2:2:2*Max_Index
            Color_Function(i,:)=[i/2-0.5,Color_Table(i,:)];
            Color_Function(i+1,:)=[i/2+0.5,Color_Table(i,:)];
        end
    case 'Gray_Scale'
        Min_Value=Parameter(1);
        Min_Gray=Parameter(2);
        Max_Value=Parameter(3);
        Max_Gray=Parameter(4);
        Color_Function=...
            [Min_Value,Min_Gray,Min_Gray,Min_Gray;...
            Max_Value,Max_Gray,Max_Gray,Max_Gray];
    case 'Rainbow'
        Min_Value=Parameter(1);
        Max_Value=Parameter(2);
        Color_Function=...
            [Min_Value,75/255,0,130/255;...
            0.2*(Max_Value-Min_Value)+Min_Value,0,0,1;...
            0.4*(Max_Value-Min_Value)+Min_Value,0,1,0;...
            0.6*(Max_Value-Min_Value)+Min_Value,1,1,0;...
            0.8*(Max_Value-Min_Value)+Min_Value,1,127/255,0;...
            Max_Value,1,0,0];
    otherwise
        error('Error in fColor_Theme: unknown theme %s.\n',Theme);
        return;
end
Color_Function(:,2:4)=Color_Function(:,2:4)*Options.Darker;
end







