function varargout=fHCP_FS_Map(Shape,Map,Color_Function,varargin)
% By Yuncong Ma, Jan. 20, 2020
% fHCP_FS_Whole_Brain(Shape,Map,Color_Function)
% Shape is a struct consists of faces and vertices
% Map is column vector with the same vertices in Shape
% Color_Function is [0,0,0,0;1,.8,.8,.8] in default
% could be generated by fColor_Theme
% Optional settings include Atlas, Atlas_Color, Brain_Color,
% Background_Color, CameraViewAngle, Material, Light, View
% Atlas should be column vector with the same vertices in Shape
% Atlas_Color is [.1,.1,.1] in default
% Brain_Color should be RGB color row vector
% Brain_Color is [.5,.5,.5] in default
% Background_Color is [0,0,0] in default
% CameraViewAngle is 5 in default
% View is [0,90] in default for top view
% Material is for function material
% Light is for function camlight, set as [-70,50;70,50] in default
% eg.
% fHCP_FS_Map(HCP_FS.Shape.LR,HCP_FS.PS_333.LR.label,fColor_Theme('Atlas',333),{'Atlas',HCP_FS.PS_333.LR.label});

Options.Atlas=[];
Options.Atlas_Color=[1 1 1]*0.1;
Options.Brain_Color=[1,1,1]*0.5;
Options.Background_Color=[0,0,0];
Options.CameraViewAngle=[5];
Options.View=[0,90];
Options.Material='default';
Options.Light=[-70,50;70,50];

Options=fOption('fHCP_FS_Map',Options,varargin);
if isempty(Options)
    return;
end

Color_Map=squeeze(fColorize(Map,Color_Function));

ps=(sum(Color_Map,2)==0 | isnan(sum(Color_Map,2)));

Color_Map(ps,:)=repmat(Options.Brain_Color,[sum(ps),1]);

if ~isempty(Options.Atlas)
    ps=Options.Atlas==0;
    Color_Map(ps,:)=repmat(Options.Atlas_Color,[sum(ps),1]);
end

ax=gca;

axis(ax,'equal');
axis(ax,'off');
hp=patch('vertices',Shape.vertices,'faces',Shape.faces,...
    'FaceVertexCData',Color_Map,'FaceColor','interp','EdgeColor','none');


for i=1:size(Options.Light,1)
    camlight(Options.Light(i,1),Options.Light(i,2));
end
lighting flat;

set(gca,'CameraViewAngle',Options.CameraViewAngle,'View',Options.View);

ax.Parent.Color=Options.Background_Color;

material(Options.Material);

if nargout
    varargout{1} = hp;
end

end